### PR TITLE
Minecraft 1.21 and java 21

### PR DESCRIPTION
**Pull request by eivinhb**
I updated the plugin to latest Fabric and java 21. Then I changed all the code to make use of dynamic registered enchantments. I have tested all the features and it seems to work fine for me. I found my protection IV in around 200 retries. :) 
I have not tested this with custom enchantments, but I guess that should work also.

### CODE REVIEW

**Comment by eivinhb** [comment]
For anyone that does not want do wait for review, you can download Artifacts from the build here:
https://github.com/eivinhb/LibrarianTradeFinder/actions/runs/9624884666

**Comment by XavierBit** [comment]
Thanks that's outstanding!

**Comment by FakeSiryakari** [comment]
W

**Comment by jsaperr** [comment]
u are so awesome

**Comment by chinese-wzq** [comment]
Great!

**Comment by someoldman** [comment]
I'm not sure if this is Minecraft or this mod so I'm just letting you know in case you want to check.   I'm using librarian-trade-finder-3.0.0 and looking from Breach IV for 14 emeralds.    I've now cycled about 45k trades and if the mod is to be believed, this combination hasn't been offered.  I have seen this enchant for 18 emeralds on these villagers but never at 14.   Density V dropped for 17 as expected.

Can you add logging to a text file so I can manually look through the trades to see why this isn't happening if you think this is a mod issue?

**Comment by eivinhb** [comment]
I don't have any knowledge where to find the lowest trade price possible at this point. I usually only care to find  the enchant and then zombie-turn the villager to lower the prices.

**Comment by FallBackITA27** [comment]
The lowest possible prices are the following:
- 5 for I
- 8 for II
- 11 for III
- 14 for IV
- 17 for V
Treasure enchants have their final prices doubled (so Mending, technically being level I, can only appear at its lowest at a price of 10 Emeralds).

**Comment by someoldman** [comment]
I did finally get it after around 40k cycles. :)

**Comment by modbibo** [comment]
Good!

**Comment by Greeenman999** [comment]
Already updated 2 months ago :) Thanks for your work however!

**Pull request closed without merging**
